# Generated by Django 4.2.16 on 2024-09-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Properties', 'verbose_name_plural': 'Properties'},
        ),
    ]
