# Generated by Django 4.2.16 on 2024-09-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name': 'Property Images', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
    ]
